apiVersion: v1 
kind: ConfigMap
metadata: 
 name: cart
 namespace: roboshop
 labels: 
    component: cart
    project: roboshop
    tier: app
spec:
 data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---
apiVersion: apps/v1 
kind: Deployment
metadata:
 name: cart
 namespace: roboshop
 labels: 
    component: cart
    project: roboshop
    tier: app
spec:
 replicas: 2
 selector:
  matchLabels:
    component: cart
    project: roboshop
    tier: app
 template:
  metadata:
   labels:
    component: cart
    project: roboshop
    tier: app
  containers:
  - name: cart
    image: ajayvallala/cart:v1
    resource:
     requests:
      cpu: "50m"
      memory: "128Mi"
     limits:
      cpu: "100m"
      memory: "256Mi"
    envFrom:
    - configMapRef:
       name: cart

---

apiVersion: v1
kind: Service
metadata:
 name: cart
 namespace: roboshop
 labels:
    component: cart
    project: roboshop
    tier: app
spec:
 selector:
  component: cart
  project: roboshop
  tier: app
 ports:
 - protocal: TCP
   port: 8080
   targetPort: 8080

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: cart
 namespace: roboshop
 labels:
    component: cart
    project: roboshop
    tier: app
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: cart
 minReplicas: 1
 maxReplicas: 10
 metrics:
 - type: Resource
   resource:
    name: cpu
    target:
     type: Utilization
     averageUtilization: 10
