apiVersion: v1 
kind: Secret
metadata:
 name: rabbitmq
 namespace: roboshop
 labels: 
   component: rabbitmq
   env: dev
   tier: database 
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="

---

apiVersion: v1 
kind: Service
metadata:
 name: rabbitmq-headless
 namespace: roboshop
 labels: 
   component: rabbitmq
   env: dev
   tier: database 
spec:
 clusterIP: None
 selector:
   component: rabbitmq
   env: dev
   tier: database 
 ports:
 - protocol: TCP
   port: 5672
   targetPort: 5672

---

apiVersion: v1 
kind: Service
metadata:
 name: rabbitmq
 namespace: roboshop
 labels: 
   component: rabbitmq
   env: dev
   tier: database 
spec:
 selector:
   component: rabbitmq
   env: dev
   tier: database 
 ports:
 - protocol: TCP
   port: 5672
   targetPort: 5672

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: rabbitmq
 namespace: roboshop
 labels: 
   component: rabbitmq
   env: dev
   tier: database 
spec:
 replicas: 2
 serviceName: "rabbitmq-headless"
 selector:
  matchLabels:
   component: rabbitmq
   env: dev
   tier: database 
 template:
  metadata:
   labels:
     component: rabbitmq
     env: dev
     tier: database 
  spec:
   containers:
   - name: rabbitmq
     image: rabbitmq:3
     volumeMounts:
     - name: rabbitmq
       mountPath: /var/lib/rabbitmq
     envFrom:
     - secretRef:
        name: rabbitmq

 volumeClaimTemplates:
 - metadata:
    name: rabbitmq
   spec:
    storageClassName: "ebs-dynamic"
    accessModes: ["ReadWriteOnce"]
    resources:
     requests:
      storage: 2Gi
  
