apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    component: redis
    env: dev
    tier: database 
spec:
  clusterIP: None
  selector:
    component: redis
    env: dev
    tier: database 
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    env: dev
    tier: database 
spec:
  selector:
    component: redis
    env: dev
    tier: database 
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    env: dev
    tier: database
spec:
  serviceName: "redis-headless"
  replicas: 2
  selector:
   matchLabels:
      component: redis
      env: dev
      tier: database
  template:
   metadata:
    labels:
      component: redis
      env: dev
      tier: database
   containers:
   - name: redis
     image: ajayvallala/redis:v1
     volumeMounts:
     - name: redis
       mountPath: /data

  # This is nothing but PVC, we can directly create here
  volumeClaimTemplates:
   metadata:
    name: redis
   spec: 
    storageClassName: "ebs-dynamic"
    accessModes: ["ReadWriteOnce"]
    resources:
     requests:
      storage: 2Gi



